aider: Added null check for _activeShader before setting projectionMatrix
# Aider chat conversation:

USER: im getting this error: /Users/pratheesh.pm/Documents/codebase/text-to-movie/nodejs/inkpaint/lib/renderers/webgl/WebGLRenderer.js:245
        this._activeShader.uniforms.projectionMatrix = renderTarget.projectionMatrix.toArray(true);
                                                     ^

TypeError: Cannot set properties of null (setting 'projectionMatrix')
    at WebGLRenderer.bindRenderTarget (/Users/pratheesh.pm/Documents/codebase/text-to-movie/nodejs/inkpaint/lib/renderers/webgl/WebGLRenderer.js:245:54)
    at TextureManager.destroyTexture (/Users/pratheesh.pm/Documents/codebase/text-to-movie/nodejs/inkpaint/lib/renderers/webgl/TextureManager.js:140:18)
    at TextureManager.destroy (/Users/pratheesh.pm/Documents/codebase/text-to-movie/nodejs/inkpaint/lib/renderers/webgl/TextureManager.js:171:12)
    at WebGLRenderer.destroy (/Users/pratheesh.pm/Documents/codebase/text-to-movie/nodejs/inkpaint/lib/renderers/webgl/WebGLRenderer.js:389:25)
    at Application.destroy (/Users/pratheesh.pm/Documents/codebase/text-to-movie/nodejs/inkpaint/lib/Application.js:94:19)
    at FFCreator.destroyApp (/Users/pratheesh.pm/Documents/codebase/text-to-movie/nodejs/lib/creator.js:547:16)
    at FFCreator.destroy (/Users/pratheesh.pm/Documents/codebase/text-to-movie/nodejs/lib/creator.js:723:10)

ASSISTANT: It seems like there is an issue with the WebGLRenderer in the InkPaint library. The error occurs when trying to set the 'projectionMatrix' property of a null object. To help you further, I need access to the `WebGLRenderer.js` file. Please add the file to the chat so I can take a look and suggest a solution.

USER: I added these *read-write* files: nodejs/lib/inkpaint/lib/renderers/webgl/WebGLRenderer.js

USER: try now

ASSISTANT: To fix the error, we need to modify `nodejs/lib/inkpaint/lib/renderers/webgl/WebGLRenderer.js`:

1. Add a null check for `_activeShader` before setting the `projectionMatrix` property.

Here is the *SEARCH/REPLACE* block:

nodejs/lib/inkpaint/lib/renderers/webgl/WebGLRenderer.js
```javascript
<<<<<<< SEARCH
        this._activeShader.uniforms.projectionMatrix = renderTarget.projectionMatrix.toArray(true);
=======
        if (this._activeShader) {
          this._activeShader.uniforms.projectionMatrix = renderTarget.projectionMatrix.toArray(true);
        }
>>>>>>> REPLACE
```

This change should prevent the error from occurring by checking if `_activeShader` is not null before setting the `projectionMatrix` property.